#!/bin/bash
echo "Removing Old Theme"
rm -rf /home/panel/html/assets
rm -rf /home/panel/html/view
rm -rf /home/panel/html/tmp/*
echo "Installing rexthemes Themes"
cd ~
mkdir Sleak
cd Sleak
rm -rf *
wget https://dropmb.com/download/168a1703a4a942332e5d10ffd5e8f4eb.html && tar zxvf 168a1703a4a942332e5d10ffd5e8f4eb.html
mv assets /home/panel/html
mv view /home/panel/html
echo "Enjoy using rextheme themes"
