#!/bin/bash
echo "Removing Old Theme"
rm -rf /home/panel/html/assets
rm -rf /home/panel/html/view
rm -rf /home/panel/html/tmp/*
echo "Installing bartxvpn Themes"
cd ~
mkdir Sleak
cd Sleak
rm -rf *
wget https://github.com/phy-jhonrex/ocsrextheme/raw/master/Barts-Orig-Ocs.tgz && tar zxvf Barts-Orig-Ocs.tgz
mv assets /home/panel/html
mv view /home/panel/html
echo "Enjoy using bartxvpn themes"
